Changed comment_data_validator
lv275python/eventually.api pull request #110
Opened 2017-12-07 22:00 UTC by noobhunters

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=738)

## Code reviewers

- [ ] @dmytrorevak
- [ ] @IvanAndrukh
- [ ] @JjuliaP
- [ ] @makarman
- [ ] @noobhunters
- [ ] @Silent777
- [ ] @Staryj812

### Second Level Review

- [ ] @ssOleg
- [ ] @lhalam

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-12-07 22:14 UTC, redmyt approved these changes

2017-12-07 22:54 UTC, redmyt requested changes

2017-12-07 22:54 UTC, dmytrorevak commented on eventually/comment/views.py
> +            return HttpResponse('sadasd', status=400)
what is `'sadasd'`? =)

2017-12-07 22:54 UTC, dmytrorevak commented on eventually/utils/validators.py
> +    comment_model_fields = ['text',
are there tests for this function?

2017-12-08 11:14 UTC, noobhunters commented on eventually/comment/views.py
> +            return HttpResponse('sadasd', status=400)
done

2017-12-08 11:14 UTC, noobhunters commented on eventually/utils/validators.py
> +    comment_model_fields = ['text',
nope

2017-12-08 11:20 UTC, JjuliaP approved these changes

2017-12-08 11:30 UTC, makarman approved these changes

2017-12-08 11:32 UTC, redmyt approved these changes

2017-12-08 11:32 UTC, merged