Add event app
lv275python/eventually.api pull request #13
Opened 2017-10-30 20:26 UTC by dmytrorevak

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=738)

## Code reviewers

- [ ] @dmytrorevak
- [ ] @IvanAndrukh
- [ ] @JjuliaP
- [ ] @makarman
- [ ] @noobhunters
- [ ] @Silent777
- [ ] @Staryj812

### Second Level Review

- [ ] @ssOleg
- [ ] @lhalam

## Summary of issue
    Added event model
    Added migration file
    Changed settings file
    Added docstrings

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-10-30 20:37 UTC, noobhunters commented on eventually/event/models.py
> +    STATUS_CHOISES = (
Choices

2017-10-30 20:39 UTC, noobhunters commented on eventually/event/views.py
> +# from django.shortcuts import render
Do you need commented lines in git repository?

2017-10-31 10:17 UTC, lhalam requested changes

2017-10-31 10:17 UTC, lhalam commented on eventually/event/models.py
> +        :return: dictionary with event's information
add example

2017-10-31 10:17 UTC, lhalam commented on eventually/event/models.py
> +            return None
maybe `pass`

2017-10-31 10:17 UTC, lhalam commented on eventually/event/models.py
> +        if status:
???

2017-10-31 10:17 UTC, lhalam commented on eventually/eventually/settings.py
> +    'event',
your app after djandoApp

2017-10-31 23:33 UTC, redmyt commented on eventually/event/views.py
> +# from django.shortcuts import render
These comments occur only for successful travis-pylint verification.

2017-11-01 00:31 UTC, dmytrorevak commented on eventually/event/models.py
> +    STATUS_CHOISES = (
fixed

2017-11-01 00:31 UTC, dmytrorevak commented on eventually/event/models.py
> +        :return: dictionary with event's information
added

2017-11-01 00:32 UTC, dmytrorevak commented on eventually/event/models.py
> +            return None
used pass

2017-11-01 00:33 UTC, dmytrorevak commented on eventually/event/models.py
> +        if status:
removed that `if` statement

2017-11-01 00:33 UTC, dmytrorevak commented on eventually/eventually/settings.py
> +    'event',
fixed

2017-11-01 06:20 UTC, Silent777 submitted a review, later dismissed

2017-11-01 11:00 UTC, lhalam commented on eventually/event/models.py
> +            'start_at': self.start_at,
convert to timestamp

2017-11-01 12:52 UTC, Silent777 submitted a review, later dismissed

2017-11-01 12:53 UTC, dmytrorevak commented on eventually/event/models.py
> +            'start_at': self.start_at,
added for all date fields

2017-11-01 16:28 UTC, lhalam submitted a review, later dismissed

2017-11-01 16:32 UTC, lhalam approved these changes

2017-11-01 16:34 UTC, merged