Add sequence diagrams
lv275python/eventually.api pull request #234
Opened 2018-02-12 15:30 UTC by tarassito

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777)

## Code reviewers

- [ ] @ashatna
- [ ] @ChristinaPastushchak
- [ ] @dotiurin
- [ ] @iryn34
- [ ] @tarassito
- [ ] @VasilHamulyak
- [ ] @VitalyiKhlivnyi
- [ ] @YurijH

### Second Level Review

- [ ] @ushevtsiv
- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-02-13 08:13 UTC, VitalyiKhlivnyi submitted a review, later dismissed

2018-02-13 08:29 UTC, ashatna reviewed
на мою думку, треба уточнити, що таке ForgetPassword

2018-02-13 08:32 UTC, ashatna submitted a review, later dismissed

2018-02-13 08:56 UTC, lhalam requested changes
To improve!

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Send email ForgetPassword Sequence Diagram.txt
> +CustomUser-->-ForgetPassword: user_id
returned CustomUser instance

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Send email ForgetPassword Sequence Diagram.txt
> +ForgetPassword->+CustomUserMail: send_password_update_letter
before add create token
send_password_update_letter(user, token)

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Set new password Sequence Diagram.txt
> +CustomUserMail-->+UI Component: get()
?token

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Set new password Sequence Diagram.txt
> +UI Component->+ForgetPassword:put(token)
before adding input fields(user) and validate field(UIcomponent) logic

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Set new password Sequence Diagram.txt
> +ForgetPassword->+CustomUser: get_by_id
before add identifier

2018-02-13 08:56 UTC, lhalam commented on documentation/sequence diagrams/authentication/Set new password Sequence Diagram.txt
> +ForgetPassword->+BD: data(new password)
add updating_password_validate

2018-02-13 13:54 UTC, tarassito commented
improved

2018-02-16 09:33 UTC, lhalam submitted a review, later dismissed

2018-02-16 11:01 UTC, ChristinaPastushchak approved these changes

2018-02-16 11:03 UTC, merged