Added cache for customuser, teams, events
lv275python/eventually.api pull request #242
Opened 2018-02-18 23:05 UTC by dotiurin

Added cache for project using Redis. 
Implemented for methods of teams/views, events/views, authentication/views

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777)

## Code reviewers

- [ ] @ashatna
- [ ] @ChristinaPastushchak
- [ ] @dotiurin
- [ ] @iryn34
- [ ] @tarassito
- [ ] @VasilHamulyak
- [ ] @VitalyiKhlivnyi
- [ ] @YurijH

### Second Level Review

- [ ] @ushevtsiv
- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-02-19 11:09 UTC, lhalam requested changes
To improve logic.

2018-02-19 11:09 UTC, lhalam commented on eventually/authentication/views.py
> +
remove  space

2018-02-19 11:09 UTC, lhalam commented on eventually/event/views.py
> +            if 'all_events' in cache:
hesh_redis_key = 'all_events_{user_id}_{event_id}_{team_id}'.format(user_id, event_id, team_id)

2018-02-20 00:39 UTC, dotiurin commented on eventually/event/views.py
> +            if 'all_events' in cache:
implemented

2018-02-20 00:39 UTC, dotiurin commented on eventually/authentication/views.py
> +
fixed

2018-02-20 08:58 UTC, lhalam reviewed
move hash logic to model methods

2018-02-26 06:39 UTC, closed without merging