updated tests for item/view, item/module
lv275python/eventually.api pull request #296
Opened 2018-05-17 12:22 UTC by anastasiyaSht

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777&view=detail&selectedIssue=LEAR-87)

## Code reviewers

- [ ] @Sokolovskyi1995
- [x] @BDubas
- [ ] @rromanitc
- [ ] @martasakal
- [ ] @Zaplatynskyi
- [ ] @aberezh

### Second Level Review

- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

## Summary of change
add tests: for item/testview : test_delete_not_success, test_delete_success, test_delete_if_user_not_mentor, test_delete_if_not_item, test_delete_if_not_topic, test_put_if_not_data, test_put_is_user_not_a_mentor, test_put_if_not_topic, test_put_if_not_item...

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-05-17 13:57 UTC, lhalam requested changes

2018-05-17 13:57 UTC, lhalam commented on eventually/tests/unittests/item/testmodel.py
> +        #
remove `#`

2018-05-17 13:57 UTC, lhalam commented on eventually/tests/unittests/item/testmodel.py
> +        #
remove `#`

2018-05-17 13:57 UTC, lhalam commented on eventually/tests/unittests/item/testmodel.py
> +        #
remove `#`

2018-05-17 13:57 UTC, lhalam commented on eventually/tests/unittests/item/testmodel.py
> +        pass
add endline

2018-05-17 13:57 UTC, lhalam commented on eventually/tests/unittests/item/testview.py
> +        self.client_second = Client()
why do you need a second client?

2018-05-17 16:58 UTC, anastasiyaSht commented on eventually/tests/unittests/item/testview.py
> +        self.client_second = Client()
I need second customer to check if user without permissions can delete topic

2018-05-22 19:03 UTC, rromanitc submitted a review, later dismissed

2018-05-22 19:27 UTC, BDubas submitted a review, later dismissed

2018-05-24 07:02 UTC, Zaplatynskyi submitted a review, later dismissed

2018-05-24 08:14 UTC, BDubas submitted a review, later dismissed

2018-05-24 09:33 UTC, lhalam submitted a review, later dismissed

2018-05-24 12:12 UTC, BDubas approved these changes

2018-05-24 12:12 UTC, martasakal approved these changes

2018-05-24 12:12 UTC, ghost approved these changes

2018-05-24 12:19 UTC, merged