update unitests for curriculum
lv275python/eventually.api pull request #298
Opened 2018-05-17 13:45 UTC by BDubas

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777&view=detail&selectedIssue=LEAR-85)

## Code reviewers

- [ ] @Sokolovskyi1995
- [ ] @anastasiyaSht
- [ ] @rromanitc
- [ ] @martasakal
- [ ] @Zaplatynskyi
- [ ] @aberezh

### Second Level Review

- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

## Summary of change

## Testing approach

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-05-17 14:10 UTC, lhalam requested changes
Coverage app curriculum  90.2%??? Why not 100%???

2018-05-17 14:10 UTC, lhalam commented on eventually/tests/unittests/curriculum/testmodel.py
> +from django.core.cache import cache
The cache should be mock

2018-05-22 18:52 UTC, rromanitc submitted a review, later dismissed

2018-05-22 22:07 UTC, aberezh submitted a review, later dismissed

2018-05-23 12:55 UTC, anastasiyaSht submitted a review, later dismissed

2018-05-23 13:46 UTC, Zaplatynskyi submitted a review, later dismissed

2018-05-24 09:33 UTC, lhalam submitted a review, later dismissed

2018-05-24 11:48 UTC, aberezh approved these changes

2018-05-24 11:53 UTC, anastasiyaSht approved these changes

2018-05-24 11:56 UTC, rromanitc approved these changes

2018-05-24 11:56 UTC, merged