update unittest for authentidication
lv275python/eventually.api pull request #300
Opened 2018-05-18 10:33 UTC by Zaplatynskyi

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777&view=detail&selectedIssue=LEAR-84)

## Code reviewers

- [ ] @Sokolovskyi1995
- [ ] @BDubas
- [ ] @anastasiyaSht
- [ ] @rromanitc
- [ ] @martasakal
- [ ] @aberezh

### Second Level Review

- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

## Summary of change

## Testing approach

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-05-18 11:26 UTC, martasakal submitted a review, later dismissed

2018-05-22 07:17 UTC, anastasiyaSht submitted a review, later dismissed

2018-05-22 19:08 UTC, rromanitc submitted a review, later dismissed

2018-05-23 00:24 UTC, aberezh commented on eventually/tests/unittests/authentication/testmodel.py
> +            with mock.patch('authentication.models.cache') as mock_cache:
75 і 76 рядки повторюються

2018-05-23 00:24 UTC, aberezh commented on eventually/tests/unittests/authentication/testmodel.py
> +                self.assertEqual(list(current_value), list(expected_value))
Може краще використати "assertListEqual"?

2018-05-23 00:24 UTC, aberezh commented on eventually/tests/unittests/authentication/testmodel.py
> +            self.assertEqual(list(current_value), list(expected_value))
І тут assertListEqual?

2018-05-23 12:14 UTC, aberezh submitted a review, later dismissed

2018-05-24 09:37 UTC, lhalam requested changes
Update to comments!

2018-05-25 08:45 UTC, anastasiyaSht submitted a review, later dismissed

2018-05-28 07:25 UTC, anastasiyaSht submitted a review, later dismissed

2018-05-28 07:29 UTC, martasakal submitted a review, later dismissed

2018-05-28 07:35 UTC, BDubas submitted a review, later dismissed

2018-05-28 08:29 UTC, lhalam submitted a review, later dismissed

2018-05-28 08:39 UTC, lhalam approved these changes

2018-05-28 08:40 UTC, BDubas approved these changes

2018-05-28 08:42 UTC, rromanitc approved these changes

2018-05-28 08:42 UTC, anastasiyaSht approved these changes

2018-05-28 08:42 UTC, martasakal approved these changes

2018-05-28 08:43 UTC, merged