added error messages to login, register and forget-password forms
lv275python/eventually.api pull request #315
Opened 2018-05-25 10:55 UTC by anastasiyaSht

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=777)

## Code reviewers

- [ ] @Sokolovskyi1995
- [ ] @BDubas
- [ ] @rromanitc
- [ ] @martasakal
- [ ] @Zaplatynskyi
- [ ] @aberezh

### Second Level Review

- [ ] @lhalam
- [ ] @ssOleg

## Summary of issue

ToDo

In Register form: disabled 'Register' button, if input data is incorrect. If a mail has been already registered, the user will see a message 'This mail is already registered.'
In Login form: disabled 'Login' button, if input data is incorrect. If user input invalid data, he will see a message 'Invalid mail or password'
I Forget-Password form: disabled 'Submit' button if input data is incorrect. 
If a mail has not been registered yet, the user will see a message 'Invalid mail.'
User cannot put new password the same, as old.

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2018-05-26 11:03 UTC, BDubas submitted a review, later dismissed

2018-05-28 04:50 UTC, Zaplatynskyi submitted a review, later dismissed

2018-05-28 07:02 UTC, rromanitc submitted a review, later dismissed

2018-05-28 08:28 UTC, martasakal submitted a review, later dismissed

2018-05-28 08:28 UTC, rromanitc submitted a review, later dismissed

2018-05-28 09:43 UTC, BDubas submitted a review, later dismissed

2018-05-28 12:35 UTC, lhalam requested changes

2018-05-28 12:35 UTC, lhalam commented on eventually/static/src/containers/registerLogin/Forget.js
> +                this.setState({sentLetter:false});
marge to
```
 this.setState({sentLetter: false,
                messageError: true});
```

2018-05-28 12:35 UTC, lhalam commented on eventually/static/src/containers/registerLogin/Login.js
> +        console.log(info);
remove `console.log`

2018-05-29 06:49 UTC, lhalam commented on eventually/static/src/containers/registerLogin/Forget.js
> +        forgetPasswordService(email).then((response) => {
use  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });

2018-05-29 06:49 UTC, lhalam commented on eventually/static/src/containers/registerLogin/Login.js
>              .then((response) => {
use .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });

2018-05-29 06:49 UTC, lhalam commented on eventually/static/src/containers/registerLogin/Forget.js
> +                this.setState({messageError:true});
use space` messageError: true`

2018-05-29 11:07 UTC, rromanitc submitted a review, later dismissed

2018-05-30 12:06 UTC, lhalam submitted a review, later dismissed

2018-05-30 12:14 UTC, aberezh approved these changes

2018-05-30 12:14 UTC, BDubas approved these changes

2018-05-30 12:17 UTC, lhalam approved these changes

2018-05-30 12:19 UTC, rromanitc approved these changes

2018-05-30 12:21 UTC, merged