Added team views
lv275python/eventually.api pull request #83
Opened 2017-11-23 15:28 UTC by makarman

Added team urls to eventually urls
Added team views

## JIRA

* [Main JIRA ticket](http://ssu-jira.softserveinc.com/browse/LVPYTP-35)
## Code reviewers

- [ ] @dmytrorevak
- [ ] @IvanAndrukh
- [ ] @JjuliaP
- [ ] @makarman
- [ ] @noobhunters
- [ ] @Silent777
- [ ] @Staryj812

### Second Level Review

- [ ] @ssOleg
- [ ] @lhalam

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-11-23 20:30 UTC, dmytrorevak commented on eventually/team/models.py
> +        data = {}
for what we add this `data` dict?

2017-11-23 20:30 UTC, dmytrorevak commented on eventually/team/models.py
> +        if members_add:
what if we would create additional functions `add_users` and `remove_users` like the model's methods?
what do you think?

2017-11-24 14:06 UTC, lhalam requested changes

2017-11-24 14:06 UTC, lhalam commented on eventually/team/models.py
> +        data = {}
roll back

2017-11-24 14:06 UTC, lhalam commented on eventually/team/views.py
> +                {
add `|`

2017-11-24 14:06 UTC, lhalam commented on eventually/team/views.py
> +        else:
unnecessary `else`

2017-11-29 16:29 UTC, lhalam approved these changes

2017-11-29 16:33 UTC, merged